ls コマンドを作るの回答
npakk/ruby-practices pull request #6
Opened 2021-08-22 17:40 UTC by npakk

2021-08-28 07:17 UTC, u1tnk requested changes

2021-08-28 07:17 UTC, u1tnk commented on 05.ls/ls.rb
> +    A = :a
一文字だと情報が増えないので `A`なら `ALL`とか分かりやすい名前にした方が良いですね。

2021-08-28 07:17 UTC, u1tnk commented on 05.ls/ls.rb
> +          'Include directory entries whose names begin with a dot (.).'
英語マニュアル 👍

2021-08-28 07:17 UTC, u1tnk commented on 05.ls/ls.rb
> +        @options[EXTRAS] = extras
`@options` は引数のオプションのイメージがあるのと、他のオプションとここだけが意味が違うので別の変数の方が良いんじゃないかと思います。

2021-08-28 07:17 UTC, u1tnk commented on 05.ls/ls.rb
> +      ftypes = { '01' => 'p', '02' => 'c', '04' => 'd', '06' => 'b', '10' => '-', '12' => 'l', '14' => 's' }
定数化してメソッド内から出した方がメソッド内の見通しが良くなります。
また、以下のように縦に並べると見やすいし、変更もしやすいですね。

```
FTYPES = {
   '01' => 'p', 
   '02' => 'c',
   '04' => 'd',
   '06' => 'b',
   '10' => '-',
   '12' => 'l',
   '14' => 's'
 }
```

2021-08-28 07:17 UTC, u1tnk commented on 05.ls/ls.rb
> +      [*not_exist, files, *dirs]
2個目の `files`だけ `*`が付いてないのは大丈夫ですか？

2021-09-20 19:18 UTC, npakk commented on 05.ls/ls.rb
> +      [*not_exist, files, *dirs]
こちらは 5aa725f1e2a9d67f2430ae2e75c3af0bc90e96db にともなって修正しております。

2021-09-21 04:59 UTC, u1tnk approved these changes
👍

2021-09-21 05:34 UTC, merged